apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  name: contrail-controller
  namespace: kube-system
  labels:
    app: contrail-cni
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Values.contrailVersion }}"
spec:
  template:
    metadata:
      labels:
        app: contrail-cni
        contrail_function: contrail-controller
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: "opencontrail.org/controller"
                operator: In
                values:
                - "true"
            - matchExpressions:
              - key: "node-role.kubernetes.io/master"
                operator: Exists
      tolerations:
      - key: node-role.kubernetes.io/master
        operator: Exists
        effect: NoSchedule
      hostNetwork: true
      containers:
      - name: contrail-controller
        image: {{ .Values.images.controller | quote }}
        imagePullPolicy: {{ default "" .Values.images.imagePullPolicy | quote }}
        securityContext:
          privileged: true
        volumeMounts:
        - mountPath: /etc/contrailctl
          name: contrailctl-controller
        - mountPath: /var/lib/cassandra
          name: configdb-data
        - mountPath: /var/lib/zookeeper
          name: zookeeper-data
      volumes:
      - name: contrailctl-controller
        configMap:
          name: contrailctl-config
          items:
          - key: controller-config
            path: controller.conf
      - name: configdb-data
        hostPath: 
          path: /var/lib/configdb
      - name: zookeeper-data
        hostPath: 
          path: /var/lib/config_zookeeper_data
