# Default values for contrail.
# (MANDATORY)
# contrailVersion - example 4.0.0.0-3042
# This variable cannot be blank.
contrailVersion: 4.0.0.0-20

# (OPTIONAL)
# hostOs - host operating system release
# ubuntu 16.04 - ubuntu
# ubuntu 14.04 - ubuntu
# centos 7.1 - centos7
# centos 7.2 - centos7
# centos 7.3 - centos7
# default hostOs: ubuntu16.04
hostOs: centos7

# (MANDATORY)
# containerOsRelease - operating system release
# ubuntu 14.04 - ubuntu14.04
# ubuntu 16.04 - ubuntu16.04
# centos 7.1 - centos7
# centos 7.2 - centos7
# centos 7.3 - centos7
containerOsRelease: ubuntu14.04

# (OPTIONAL)
# Docker repository
imageRepo: 10.84.5.71:5000

# Global configurations
#
global:

  # (MANDATORY)
  # controller_nodes 
  controller_nodes: 
    - 10.87.65.30
  
  # (OPTIONAL)
  # If analyticsdb nodes are different from controller_nodes
  # Example:
  # analyticsdb_nodes: 
  #  - 10.87.65.30

  # (OPTIONAL)
  # If analytics nodes are different from controller_nodes
  # Example:
  # analytics_nodes: 
  #  - 10.87.65.30
 
  #(MANDATORY) 
  # cloud_orchestrator: values - kubernetes, mesos, openshift, openstack
  cloud_orchestrator: kubernetes

#
# webui configurations
#
#webui:
  # (OPTIONAL)
  # http listen port: default 8080
  # Example: 
  # http_listen_port: 8085

  # (OPTIONAL)
  # https_listen_port: default 8143
  # https_listen_port:

#
# agent configurations
#
agent:
  # (MANDATORY)
  # vrouter_physical_interface - physical interface to use for vrouter
  vrouter_physical_interface: em1

#
# Other optional parameters which rarely changed
#

## Specify a imagePullPolicy: 'Always' if imageTag is 'latest', else set to 'IfNotPresent'.
## ref: https://kubernetes.io/docs/user-guide/images/#pre-pulling-images
##
# imagePullPolicy:

# (OPTIONAL)
# If manually loaded docker images, then give the contrail container image names
# controllerImageName: contrail-controller-ubuntu-16.04:4.0.0.0-20
# analyticsImageName: contrail-analytics-ubuntu-16.04:4.0.0.0-20
# analyticsdbImageName: contrail-analyticsdb-ubuntu-16.04:4.0.0.0-20
# kubeManagerImageName: contrail-kube-manager-ubuntu-16.04:4.0.0.0-20
# agentImageName: contrail-agent-ubuntu-16.04:4.0.0.0-20
# compilerImageName: contrail-vrouter-compiler-centos7:4.0.0.0-20

#
# kubernetes configurations
#
kubernetes:

  # (OPTIONAL)
  # If contrail controller node is differnet then the k8s master node
  # Then give the IP address of the kubernetes_api_server
  # Example:
  # kubernetes_api_server: 10.84.18.8

  # (OPTIONAL)
  # Name of the kubernetes cluster being provisioned
  # Default value: "k8s-default"
  # Example:
  # cluster_name: k8s-default
  
  # Access token to connect to kubernetes API server
  # Default value: ""
  kubernetes_access_token: ""

  # (OPTIONAL)
  # Pod subnet 
  # Default value: "10.32.0.0/12"
  # Example:
  # kubernetes_pod_subnets: "10.87.45.0/24"

  # (OPTIONAL)
  # Service subnet
  # Default value: "10.96.0.0/12"
  # Example:
  # kubernetes_service_subnets: "10.87.46.0/24"
  
  # (OPTIONAL)
  # Cluster project used in contrail
  # Default value: {'domain': 'default-domain', 'project': 'default'}
  # Example:
  # kubernetes_cluster_project: "{'domain': 'default-domain', 'project': 'default'}"

  # (OPTIONAL)
  # Kubernetes FloatingIpPool to be used for service/ingress.
  # Example:
  # kubernetes_public_fip_pool: {'domain': 'domain-name', 'project': 'project-name', 'network': 'network-name', 'name': 'fip-pool-name' }
