---
apiVersion: v1
kind: ConfigMap
metadata:
  name: contrail-config
data:
  global-config: |-
    [GLOBAL]
    cloud_orchestrator = kubernetes
    sandesh_ssl_enable = False
    enable_config_service = True
    enable_control_service = True
    enable_webui_service = True
    introspect_ssl_enable = False
  agent-config: |-
    [AGENT]
    compile_vrouter_module = True
    vrouter_physical_interface = p4p1
  kubemanager-config: |-
    [KUBERNETES]
    cluster_name = k8s-default
    cluster_project = {'domain': 'default-domain', 'project': 'default'}
    cluster_network = {}
    service_subnets = 10.96.0.0/12
    pod_subnets = 10.32.0.0/12
    token =
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: contrail-config-modifier
data:
  contrailctl_modifier.py: |-
    import os
    import sys
    import ConfigParser
    import time

    # Random sleep timer
    print "sleep for 10000"
    time.sleep(100000)
    
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: contrail-hosts
data:
  hosts: |-
    127.0.0.1       localhost
    127.0.1.1       minikube
    10.0.0.1        kubernetes.default

---
apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  name: contrail-controller
  labels:
    app: contrail-controller
spec:
  template:
    metadata:
      labels:
        app: contrail-controller
    spec:
      tolerations:
      - key: node-role.kubernetes.io/master
        operator: Exists
        effect: NoSchedule
      hostNetwork: true
      serviceAccountName: contrail-controller
      initContainers:
      - name: contrail-toolkit
        image: "madhukar32/contrail-toolkit:4.0.0.0-6"
        imagePullPolicy: ""
        env:
        - name: podIp
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
        - name: contrail_role
          value: controller
        volumeMounts:
        - mountPath: /etc/
          name: hosts
      containers:
      - name: contrail-controller
        image: "10.84.5.71:5000/contrail-controller-ubuntu16.04:4.0.0.0-20"
        imagePullPolicy: ""
        command: ["/usr/bin/python", "/tmp/contrailctl_modifier.py"]
        securityContext:
          privileged: true
        volumeMounts:
        - mountPath: /etc/contrailctl
          name: contrail-config
        - mountPath: /var/lib/cassandra
          name: configdb-data
        - mountPath: /var/lib/zookeeper
          name: zookeeper-data
        - mountPath: /tmp/
          name: python
      volumes:
      - name: contrail-config
        configMap:
          name: contrail-config
      - name: hosts
        configMap:
          name: contrail-hosts
          items:
          - key: hosts
            path: hosts
      - name: python
        configMap:
          name: contrail-config-modifier
          items:
          - key: contrailctl_modifier.py
            path: contrailctl_modifier.py
      - name: configdb-data
        emptyDir: {}
      - name: zookeeper-data
        emptyDir: {}
---
apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  name: contrail-analyticsdb
  labels:
    app: contrail-analyticsdb
spec:
  template:
    metadata:
      labels:
        app: contrail-analyticsdb
    spec:
      tolerations:
      - key: node-role.kubernetes.io/master
        operator: Exists
        effect: NoSchedule
      hostNetwork: true
      serviceAccountName: contrail-controller
      initContainers:
      - name: contrail-toolkit
        image: "madhukar32/contrail-toolkit:4.0.0.0-6"
        imagePullPolicy: ""
        command: ["python", "/configmap_modifier.py"]
        env:
        - name: podIp
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
        - name: contrail_role
          value: analyticsdb
        volumeMounts:
        - mountPath: /etc/
          name: hosts
      containers:
      - name: contrail-analyticsdb
        image: "10.84.5.71:5000/contrail-analyticsdb-ubuntu16.04:4.0.0.0-20"
        command: ["/usr/bin/python", "/tmp/contrailctl_modifier.py"]
        imagePullPolicy: ""
        securityContext:
          privileged: true
        volumeMounts:
        - mountPath: /etc/contrailctl
          name: contrail-config
        - mountPath: /var/lib/cassandra
          name: analyticsdb-data
        - mountPath: /tmp/
          name: python
      volumes:
      - name: contrail-config
        configMap:
          name: contrail-config
      - name: python
        configMap:
          name: contrail-config-modifier
          items:
          - key: contrailctl_modifier.py
            path: contrailctl_modifier.py
      - name: analyticsdb-data
        emptyDir: {}
      - name: hosts
        configMap:
          name: contrail-hosts
          items:
          - key: hosts
            path: hosts
---
apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  name: contrail-analytics
  labels:
    app: contrail-analytics
spec:
  template:
    metadata:
      labels:
        app: contrail-analytics
    spec:
      tolerations:
      - key: node-role.kubernetes.io/master
        operator: Exists
        effect: NoSchedule
      hostNetwork: true
      serviceAccountName: contrail-controller
      initContainers:
      - name: contrail-toolkit
        image: "madhukar32/contrail-toolkit:4.0.0.0-6"
        imagePullPolicy: ""
        command: ["python", "/configmap_modifier.py"]
        env:
        - name: podIp
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
        - name: contrail_role
          value: analytics
        volumeMounts:
        - mountPath: /etc/
          name: hosts
      containers:
      - name: contrail-analytics
        image: "10.84.5.71:5000/contrail-analytics-ubuntu16.04:4.0.0.0-20"
        imagePullPolicy: ""
        command: ["/usr/bin/python", "/tmp/contrailctl_modifier.py"]
        securityContext:
          privileged: true
        volumeMounts:
        - mountPath: /etc/contrailctl
          name: contrail-config
      volumes:
      - name: contrail-config
        configMap:
          name: contrail-config
      - name: python
        configMap:
          name: contrail-config-modifier
          items:
          - key: contrailctl_modifier.py
            path: contrailctl_modifier.py
      - name: hosts
        configMap:
          name: contrail-hosts
          items:
          - key: hosts
            path: hosts
---
apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  name: contrail-kube-manager
  labels:
    app: contrail-kube-manager
spec:
  template:
    metadata:
      labels:
        app: contrail-kube-manager
    spec:
      tolerations:
      - key: node-role.kubernetes.io/master
        operator: Exists
        effect: NoSchedule
      serviceAccountName: contrail-kube-manager
      initContainers:
      - name: contrail-toolkit
        image: "madhukar32/contrail-toolkit:4.0.0.0-6"
        imagePullPolicy: ""
        command: ["python", "/configmap_modifier.py"]
        env:
        - name: podIp
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
        - name: contrail_role
          value: kubemanager
        volumeMounts:
        - mountPath: /etc/
          name: hosts
      hostNetwork: true
      containers:
      - name: contrail-kube-manager
        image: "10.84.5.71:5000/contrail-kube-manager-ubuntu16.04:4.0.0.0-20"
        imagePullPolicy: ""
        command: ["/usr/bin/python", "/tmp/contrailctl_modifier.py"]
        securityContext:
          privileged: true
        volumeMounts:
        - mountPath: /tmp/contrailctl
          name: contrail-config
        - mountPath: /tmp/
          name: python
      volumes:
      - name: contrail-config
        configMap:
          name: contrail-config
      - name: python
        configMap:
          name: contrail-config-modifier
          items:
          - key: contrailctl_modifier.py
            path: contrailctl_modifier.py
      - name: hosts
        configMap:
          name: contrail-hosts
          items:
          - key: hosts
            path: hosts
---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: contrail-controller
rules:
  - apiGroups: [""]
    resources:
      - configmaps
    verbs:
      - update
      - patch
  - apiGroups:
      - extensions
      - apps
    resources:
      - daemonsets
    verbs:
      - get
      - watch
      - list
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: contrail-controller
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: contrail-controller
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: contrail-controller
subjects:
- kind: ServiceAccount
  name: contrail-controller
  namespace: default
---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: contrail-kube-manager
  namespace: default
rules:
  - apiGroups: ["*"]
    resources: ["*"]
    verbs: ["*"]
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: contrail-kube-manager
  namespace: default
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: contrail-kube-manager
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: contrail-kube-manager
subjects:
- kind: ServiceAccount
  name: contrail-kube-manager
  namespace: default
